---
name: CD

on:
  push:
    branches:
      - master

jobs:
  release-please:
    name: Release Please # https://github.com/googleapis/release-please
    runs-on: ubuntu-latest
    steps:
      - name: Release Please
        uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: rust
          package-name: release-please-action
          bump-minor-pre-major: true
          bump-patch-for-minor-pre-major: true
          extra-files: |
            README.md

      - name: Checkout
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/checkout@v2

      - name: Install Rust
        if: ${{ steps.release.outputs.release_created }}
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Cache
        if: ${{ steps.release.outputs.release_created }}
        uses: Swatinem/rust-cache@v1

      - name: Publish to crates.io
        if: ${{ steps.release.outputs.release_created }}
        run: |
          cargo publish --token "${{ secrets.CARGO_REGISTRY_TOKEN }}"
